# Header
menu:
  Home: /
  About: /about

# Favicon
favicon_url:

# Default Image for Posts
default_cover_image: images/default.jpg

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
email_url: 
twitter_url:
facebook_url:
instagram_url: https://www.instagram.com/airisse__/
linkedin_url: https://www.linkedin.com/in/yi-feng-651292161/
dribbble_url:
github_url:
googleplus_url:
behance_url:
fivehundredpx_url:

# Disqus comments
disqus_shortname:
